using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.Imperial.Medieval.Praises;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.Imperial.Medieval.Praises;

[GenerateTypedNameReferences]
public sealed partial class PraiseViewWindow : DefaultWindow
{
    public PraiseViewWindow(IEnumerable<PraiseViewRecord> praises)
    {
        RobustXamlLoader.Load(this);

        foreach (PraiseViewRecord record in praises)
        {
            RecordContainer.AddChild(new Label { Text = $"{record.Date} - {record.Reason}" });
        }
    }
}
