using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Imperial.Medieval.UniversalLock.Lock;

[GenerateTypedNameReferences]
public sealed partial class UniversalKeyWindow : DefaultWindow
{
    public Action<int[]>? OnSetCode;
    private List<LineEdit> _inputs = new();
    private List<Slider> _sliders = new();
    private const int MaxToothValue = 32;
    private const int MaxPossibleLength = 32;

    public UniversalKeyWindow()
    {
        RobustXamlLoader.Load(this);

        SetCodeButton.OnPressed += _ => SubmitCode();

        LengthSlider.OnValueChanged += args => OnLengthSliderChanged((int)args.Value);
        LengthInput.OnTextChanged += args => OnLengthInputChanged(args.Text);

        SetCodeButton.Text = Loc.GetString("UniversalKey-ui-forge-button");
        Title = Loc.GetString("UniversalKey-ui-title");
    }

    public void UpdateState()
    {
        InfoLabel.Text = $"{Loc.GetString("UniversalLock-ui-setup-allowed-value-from")} 0 - {MaxToothValue}";

        LengthSlider.MaxValue = MaxPossibleLength;

        if (LengthSlider.Value < 1)
            LengthSlider.Value = 1;

        LengthInput.Text = ((int)LengthSlider.Value).ToString();
        BuildInputs((int)LengthSlider.Value);
    }

    private void OnLengthSliderChanged(int newLength)
    {
        if (int.TryParse(LengthInput.Text, out var currentInputVal) && currentInputVal != newLength)
        {
            LengthInput.Text = newLength.ToString();
        }

        BuildInputs(newLength);
    }

    private void OnLengthInputChanged(string text)
    {
        if (string.IsNullOrEmpty(text))
            return;

        if (int.TryParse(text, out var val))
        {
            var maxTeeth = (int)LengthSlider.MaxValue;

            if (val < 1) val = 1;
            if (val > maxTeeth) val = maxTeeth;

            if ((int)LengthSlider.Value != val)
            {
                LengthSlider.Value = val;
            }
        }
    }

    private void BuildInputs(int length)
    {
        int currentLength = _sliders.Count;

        // Сценарий 1: Игрок увеличил количество зубцов — ДОБАВЛЯЕМ новые в конец
        if (length > currentLength)
        {
            for (int i = currentLength; i < length; i++)
            {
                var rowContainer = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    SeparationOverride = 10
                };

                var slider = new Slider
                {
                    MinValue = 0,
                    MaxValue = MaxToothValue,
                    Rounded = true,
                    HorizontalExpand = true,
                    Value = 0
                };

                var input = new LineEdit
                {
                    MinWidth = 45,
                    MaxWidth = 45,
                    Text = "0",
                    HorizontalAlignment = HAlignment.Center
                };

                // Локальные переменные для безопасного захвата в лямбда-выражениях
                var currentSlider = slider;
                var currentInput = input;

                currentSlider.OnValueChanged += val =>
                {
                    currentInput.Text = ((int)val.Value).ToString();
                };

                currentInput.OnTextChanged += args =>
                {
                    if (int.TryParse(args.Text, out var val))
                    {
                        if (val < 0) val = 0;
                        if (val > MaxToothValue) val = MaxToothValue;

                        currentSlider.Value = val;
                    }
                };

                _sliders.Add(currentSlider);
                _inputs.Add(currentInput);

                rowContainer.AddChild(currentSlider);
                rowContainer.AddChild(currentInput);
                InputsContainer.AddChild(rowContainer);
            }
        }
        // Сценарий 2: Игрок уменьшил количество зубцов — УДАЛЯЕМ лишние с конца
        else if (length < currentLength)
        {
            for (int i = currentLength - 1; i >= length; i--)
            {
                var slider = _sliders[i];
                var input = _inputs[i];

                // Находим родительский горизонтальный BoxContainer (строку) этого зуба
                var rowContainer = slider.Parent;
                if (rowContainer != null)
                {
                    InputsContainer.RemoveChild(rowContainer);
                    rowContainer.Dispose(); // Это автоматически удалит и очистит slider и input внутри него
                }

                _sliders.RemoveAt(i);
                _inputs.RemoveAt(i);
            }
        }
    }

    private void SubmitCode()
    {
        var code = new int[_inputs.Count];

        for (int i = 0; i < _inputs.Count; i++)
        {
            if (int.TryParse(_inputs[i].Text, out var val))
            {
                if (val < 0 || val > MaxToothValue)
                    return;

                code[i] = val;
            }
            else
            {
                code[i] = 0;
            }
        }

        LengthSlider.Disabled = true;
        LengthInput.Editable = false;

        foreach (var slider in _sliders) slider.Disabled = true;
        foreach (var input in _inputs) input.Editable = false;
        SetCodeButton.Disabled = true;

        OnSetCode?.Invoke(code);
    }
}
